Docs file change
ABSESpy/ABSESpy pull request #93
Opened 2024-12-11 07:16 UTC by xyuechen

#92 issue.So add a file for contribution.

2024-12-11 09:06 UTC, SongshGeo requested changes
Could you please polish it with a better ["Markdown style"](https://team.songshgeo.com/%E5%B7%A5%E4%BD%9C%E5%8F%B0/%E6%8C%87%E5%8D%97/markdown-%E6%96%87%E6%A1%A3%E9%A3%8E%E6%A0%BC) by referring [Markdown Lint](https://github.com/DavidAnson/markdownlint)?

2024-12-14 19:27 UTC, SongshGeo commented
谢谢作出格式更新。我记得我有提到，说加上我们这个项目的开发方案？比如如何使用 poetry 配置开发环境，如何使用 pytest 测试代码库。

2024-12-14 19:28 UTC, SongshGeo requested changes
谢谢作出格式更新。我记得我有提到，说加上我们这个项目的开发方案？比如如何使用 poetry 配置开发环境，如何使用 pytest 测试代码库。对了，学习 mesa，我们也加上 git config rebase，让 PR 里的贡献历史更线性，更简洁

2024-12-14 19:28 UTC, SongshGeo commented on docs/home/comtributing.md
> +## Test and code standard
我认为这里应该更细致一些，教如何测试，我的项目这里使用 pytest 框架

2024-12-15 13:27 UTC, xyuechen commented on docs/home/comtributing.md
> +## Test and code standard
感谢您的反馈，我将做出对应的修改

2024-12-19 12:38 UTC, SongshGeo approved these changes

2024-12-19 12:38 UTC, merged